import { AgentAlreadyExistsError, ConfigIO, setEnvVar } from '../../../lib';
import { ExportHarnessError, ValidationError } from '../../../lib/errors/types';
import { AgentNameSchema } from '../../../schema';
import type { AgentEnvSpec, BuildType, Credential } from '../../../schema';
import { getErrorMessage } from '../../errors';
import type { AttributeRecorder } from '../../telemetry/cli-command-run.js';
import { withCommandRunTelemetry } from '../../telemetry/cli-command-run.js';
import type { CommandAttrs } from '../../telemetry/schemas/command-run.js';
import {
  BuildType as TelemetryBuildType,
  ModelProvider as TelemetryModelProvider,
  standardize,
} from '../../telemetry/schemas/common-shapes.js';
import { StrandsRenderer } from '../../templates/StrandsRenderer';
import { EXPORT_NOTES_FILENAME } from './constants';
import { mapHarnessToExportConfig } from './harness-mapper';
import { resolveHarnessContext } from './harness-resolver';
import type { ExportHarnessOptions, ExportNote, ResolvedHarnessContext } from './types';
import { execSync } from 'node:child_process';
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

export interface ExportHarnessProgress {
  onProgress?: (message: string) => void;
}

export async function handleExportHarness(
  options: ExportHarnessOptions,
  progress?: ExportHarnessProgress
): Promise<
  { success: true; agentName: string; agentPath: string; notesPath: string } | { success: false; error: Error }
> {
  const log = (msg: string) => progress?.onProgress?.(msg);

  return withCommandRunTelemetry(
    'export.harness',
    {} as CommandAttrs<'export.harness'>,
    async (recorder: AttributeRecorder<CommandAttrs<'export.harness'>>) => {
      const harnessName = options.name;
      if (!harnessName) {
        return { success: false as const, error: new ValidationError('--name is required in non-interactive mode') };
      }

      const targetAgentName = options.targetAgentName ?? `${harnessName}Agent`;
      const parsedAgentName = AgentNameSchema.safeParse(targetAgentName);
      if (!parsedAgentName.success) {
        return {
          success: false as const,
          error: new ValidationError(
            `Invalid --target-agent-name "${targetAgentName}": ${parsedAgentName.error.issues[0]?.message ?? 'invalid name'}`
          ),
        };
      }

      const buildOverride = options.build as BuildType | undefined;

      const VALID_BUILD_TYPES = new Set<string>(['CodeZip', 'Container']);
      if (buildOverride && !VALID_BUILD_TYPES.has(buildOverride)) {
        return {
          success: false as const,
          error: new ValidationError(`Invalid --build value "${buildOverride}". Expected CodeZip or Container.`),
        };
      }

      // 1. Resolve all on-disk inputs
      log('Reading harness configuration');
      let context: Awaited<ReturnType<typeof resolveHarnessContext>>;
      try {
        context = await resolveHarnessContext(harnessName, targetAgentName);
      } catch (err) {
        return { success: false as const, error: err instanceof Error ? err : new Error(String(err)) };
      }

      // 2. Map harness spec to render config + agent env spec
      log('Mapping to Strands template config');
      const { renderConfig, agentEnvSpec, credentialEntry, mcpCredentialEntries } = mapHarnessToExportConfig(
        context,
        buildOverride
      );

      // The target directory is guaranteed not to pre-exist (resolveHarnessContext throws if it
      // does), so anything written below is created by this export. Remove it on failure to avoid
      // leaving an orphan directory with no matching agentcore.json entry.
      const agentDir = join(context.projectRoot, 'app', targetAgentName);
      const cleanupAgentDir = () => {
        try {
          rmSync(agentDir, { recursive: true, force: true });
        } catch {
          // best-effort cleanup — ignore failures
        }
      };

      // 3. Copy Dockerfile + supporting harness directories (e.g. path_skill/, assets/)
      //    Harness files that are NOT copied: harness.json, system-prompt.md (regenerated by export)
      const HARNESS_SKIP_FILES = new Set(['harness.json', 'system-prompt.md']);
      if (context.spec.dockerfile) {
        const harnessDir = join(context.projectRoot, 'app', harnessName);
        const dockerfileSrc = join(harnessDir, context.spec.dockerfile);
        if (existsSync(dockerfileSrc)) {
          mkdirSync(agentDir, { recursive: true });
          copyFileSync(dockerfileSrc, join(agentDir, context.spec.dockerfile));
        } else {
          context.exportNotes.push({
            category: `Dockerfile not found — create ${context.spec.dockerfile} before deploying`,
            message:
              `The harness references dockerfile: "${context.spec.dockerfile}" but no such file exists in ` +
              `app/${harnessName}/. Create a Dockerfile at app/${targetAgentName}/${context.spec.dockerfile} ` +
              `before running \`agentcore deploy\`.`,
          });
        }
        // Copy all non-file entries (directories) and non-skipped files from the harness dir
        if (existsSync(harnessDir)) {
          cpSync(harnessDir, agentDir, {
            recursive: true,
            filter: src => {
              const name = basename(src);
              return !HARNESS_SKIP_FILES.has(name);
            },
          });
        }
      }

      // 4. Generate Dockerfile stub for containerUri
      if (context.spec.containerUri && renderConfig.buildType === 'Container') {
        mkdirSync(agentDir, { recursive: true });
        writeDockerfileStub(agentDir, context.spec.containerUri);
      }

      // 5. Render Strands agent code
      log('Rendering agent code');
      try {
        const renderer = new StrandsRenderer(renderConfig);
        await renderer.render({ outputDir: context.projectRoot });
      } catch (err) {
        cleanupAgentDir();
        return {
          success: false as const,
          error: new ExportHarnessError(
            `Failed to render agent code for "${targetAgentName}": ${getErrorMessage(err)}`,
            {
              cause: err instanceof Error ? err : undefined,
            }
          ),
        };
      }

      // 5b. Generate uv.lock for Container builds (required by the Dockerfile's uv sync step)
      if (renderConfig.buildType === 'Container') {
        log('Generating uv.lock for container build');
        try {
          execSync('uv lock', { cwd: agentDir, stdio: 'pipe' });
        } catch {
          // uv not installed or failed — add a note and continue; user can run manually
          context.exportNotes.push({
            category: 'uv.lock missing — run `uv lock` before deploying',
            message:
              `The container Dockerfile requires a uv.lock file. Run \`uv lock\` in ` +
              `app/${targetAgentName}/ before running \`agentcore deploy\`.`,
          });
        }
      }

      // 6. Write agent to agentcore.json
      log('Updating agentcore.json');
      try {
        await writeExportedAgentToProject(agentEnvSpec, context, credentialEntry, mcpCredentialEntries);
      } catch (err) {
        cleanupAgentDir();
        return { success: false as const, error: err instanceof Error ? err : new Error(String(err)) };
      }

      // 6c. Write MCP header credential values to .env.local for local development
      for (const { envVarName, value } of mcpCredentialEntries) {
        await setEnvVar(envVarName, value, context.configBaseDir);
      }

      // 6b. Warn if no deploy targets are configured
      const configIO = new ConfigIO({ baseDir: context.configBaseDir });
      const targets = await configIO.readAWSDeploymentTargets().catch(() => []);
      if (targets.length === 0) {
        context.exportNotes.push({
          category: 'No AWS deployment target configured',
          message:
            'aws-targets.json is empty — running `agentcore deploy` will fail with "Target \\"default\\" not found". ' +
            'Add a deployment target first:\n\n' +
            '  agentcore deploy  (interactive mode will prompt for account/region)\n\n' +
            'Or edit agentcore/aws-targets.json manually:\n\n' +
            '  [{ "name": "default", "account": "<account-id>", "region": "<region>" }]',
        });
      }

      // 7. Write EXPORT_NOTES.md
      log('Writing EXPORT_NOTES.md');
      writeExportNotes(context.exportNotes, harnessName, targetAgentName, agentDir);

      // Record telemetry attrs after all work is done
      recorder.set({
        build_type: standardize(TelemetryBuildType, renderConfig.buildType ?? 'CodeZip'),
        model_provider: standardize(TelemetryModelProvider, renderConfig.modelProvider),
        has_memory: renderConfig.hasMemory,
        has_gateway: renderConfig.hasGateway,
        has_container: renderConfig.buildType === 'Container',
        has_execution_limits: !!renderConfig.hasExecutionLimits,
        notes_count: context.exportNotes.length,
      });

      return {
        success: true as const,
        agentName: targetAgentName,
        agentPath: agentDir,
        notesPath: join(agentDir, EXPORT_NOTES_FILENAME),
      };
    }
  );
}

// ============================================================================
// Write agent entry to agentcore.json
// ============================================================================

async function writeExportedAgentToProject(
  agentEnvSpec: AgentEnvSpec,
  context: ResolvedHarnessContext,
  credentialEntry: Credential | null,
  mcpCredentialEntries: { credential: Credential }[]
): Promise<void> {
  const configIO = new ConfigIO({ baseDir: context.configBaseDir });
  const project = await configIO.readProjectSpec();

  if (project.runtimes.some(r => r.name === agentEnvSpec.name)) {
    throw new AgentAlreadyExistsError(agentEnvSpec.name);
  }

  project.runtimes.push(agentEnvSpec);

  if (credentialEntry && !project.credentials.some(c => c.name === credentialEntry.name)) {
    project.credentials.push(credentialEntry);
  }

  for (const { credential } of mcpCredentialEntries) {
    if (!project.credentials.some(c => c.name === credential.name)) {
      project.credentials.push(credential);
    }
  }

  await configIO.writeProjectSpec(project);
}

// ============================================================================
// Write EXPORT_NOTES.md
// ============================================================================

function readStrandsVersion(agentDir: string): string {
  try {
    const pyproject = readFileSync(join(agentDir, 'pyproject.toml'), 'utf8');
    const match = /strands-agents\s*(>=\s*[\d.]+)/.exec(pyproject);
    return match ? `strands-agents ${match[1]}` : 'strands-agents (version unknown)';
  } catch {
    return 'strands-agents (version unknown)';
  }
}

function writeExportNotes(notes: ExportNote[], harnessName: string, agentName: string, agentDir: string): void {
  const today = new Date().toISOString().split('T')[0];
  const strandsVersion = readStrandsVersion(agentDir);
  const lines: string[] = [
    `# Export Notes — ${harnessName} → ${agentName}`,
    '',
    `Exported on: ${today}`,
    `Strands version: ${strandsVersion}`,
    `Source harness: agentcore/app/${harnessName}/harness.json`,
    `Generated agent: app/${agentName}/`,
    '',
  ];

  if (notes.length === 0) {
    lines.push('No manual steps required.');
  } else {
    lines.push('## Items requiring manual follow-up');
    for (const note of notes) {
      lines.push('');
      lines.push(`### ${note.category}`);
      lines.push(note.message);
    }
  }

  lines.push('');

  const outPath = join(agentDir, EXPORT_NOTES_FILENAME);
  writeFileSync(outPath, lines.join('\n'), 'utf8');
}

// ============================================================================
// Dockerfile stub for containerUri harnesses
// ============================================================================

function writeDockerfileStub(agentDir: string, containerUri: string): void {
  const content = [
    `# Base image from the source harness: ${containerUri}`,
    '# The generated Strands agent is layered on top. If the base image does not',
    '# include Python 3.12+ or uv, add install steps before the COPY/RUN below.',
    `FROM ${containerUri}`,
    '',
    'RUN pip install --no-cache-dir uv',
    '',
    'WORKDIR /app',
    '',
    'ARG UV_DEFAULT_INDEX',
    'ARG UV_INDEX',
    '',
    'ENV UV_SYSTEM_PYTHON=1 \\',
    '    UV_COMPILE_BYTECODE=1 \\',
    '    UV_NO_PROGRESS=1 \\',
    '    PYTHONUNBUFFERED=1 \\',
    '    DOCKER_CONTAINER=1 \\',
    '    UV_DEFAULT_INDEX=${UV_DEFAULT_INDEX} \\',
    '    UV_INDEX=${UV_INDEX}',
    '',
    'RUN useradd -m -u 1000 bedrock_agentcore',
    '',
    'COPY pyproject.toml uv.lock ./',
    'RUN uv sync --frozen --no-dev --no-install-project',
    '',
    'COPY --chown=bedrock_agentcore:bedrock_agentcore . .',
    'RUN uv sync --frozen --no-dev',
    '',
    'USER bedrock_agentcore',
    '',
    'EXPOSE 8080 8000 9000',
    '',
    'CMD ["python", "-m", "main"]',
    '',
  ].join('\n');

  writeFileSync(join(agentDir, 'Dockerfile'), content, 'utf8');
}
