"""Payment capability -- auto-generated by agentcore CLI.

Configures AgentCorePaymentsPlugin for Strands agents.
Manager config is auto-discovered from AGENTCORE_PAYMENT_*
environment variables set at deploy time.

Uses a per-invocation factory pattern so each request gets its own
plugin instance with the correct user_id, instrument_id, and session_id.
This prevents concurrency bugs where one user's payment context
could leak to another user's request.

Uses the official SDK plugin which handles:
- x402 v1 (body-based) and v2 (header-based) payment detection
- Automatic 402 response interception and payment processing
- Retry limiting (max 3 payment retries per tool use)
- Error management and logging
"""
import os
import logging

import boto3
from bedrock_agentcore.payments.integrations.strands import AgentCorePaymentsPlugin
from bedrock_agentcore.payments.integrations.config import AgentCorePaymentsPluginConfig

logger = logging.getLogger(__name__)

PAYMENT_SYSTEM_PROMPT = """
You have payment capabilities via the x402 protocol:
- Use http_request to call HTTP endpoints. 402 Payment Required responses are settled automatically by the plugin and the call is retried.
- Use get_payment_session to check your remaining budget before expensive operations
- Use get_payment_instrument_balance to check wallet USDC balance
- Use list_payment_instruments to see available payment instruments
- If budget is low, inform the user before proceeding with paid requests
"""

_manager_arn = None
_connector_id = None
_process_payment_role_arn = None
_name_segment = None
_region = None
_auth_mode = None
_manager_count = 0
for key, value in os.environ.items():
    if key.startswith("AGENTCORE_PAYMENT_") and key.endswith("_MANAGER_ARN"):
        if _manager_arn is None:
            _manager_arn = value
            _name_segment = key[len("AGENTCORE_PAYMENT_"):-len("_MANAGER_ARN")]
        _manager_count += 1
if _manager_count > 1:
    logger.warning(
        "Multiple payment managers detected in environment. Using the first one found. "
        "Remove extra AGENTCORE_PAYMENT_*_MANAGER_ARN env vars to eliminate ambiguity."
    )
_region = os.getenv("AWS_REGION")

_prefix = f"AGENTCORE_PAYMENT_{_name_segment}_" if _name_segment else "AGENTCORE_PAYMENT_"
_auth_mode = os.getenv(f"{_prefix}AUTH_MODE", "sigv4")
_connector_id = os.getenv(f"{_prefix}CONNECTOR_ID")
_process_payment_role_arn = os.getenv(f"{_prefix}PROCESS_PAYMENT_ROLE_ARN")
_auto_payment = os.getenv(f"{_prefix}AUTO_PAYMENT", "true").lower() == "true"
_allowlist_raw = os.getenv(f"{_prefix}TOOL_ALLOWLIST")
_allowlist = _allowlist_raw.split(",") if _allowlist_raw else None
_network_prefs_raw = os.getenv(f"{_prefix}NETWORK_PREFERENCES")
_network_prefs = _network_prefs_raw.split(",") if _network_prefs_raw else None

if not _manager_arn:
    logger.warning("No payment manager config found in environment")
if not _connector_id:
    logger.warning("No payment connector config found in environment")


def _assume_role_session(role_arn):
    """Assume an IAM role and return a boto3 session with temporary credentials."""
    sts = boto3.client("sts", region_name=_region)
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="agentcore-payment-plugin",
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
        region_name=_region,
    )


def create_payments_plugin(user_id, instrument_id=None, session_id=None):
    """Create a fresh plugin instance per invocation.

    Args:
        user_id: From invocation context (required for SigV4, derived from JWT for bearer)
        instrument_id: From invocation payload (created by app backend per user)
        session_id: From invocation payload (created by app backend per conversation)

    Returns:
        AgentCorePaymentsPlugin instance, or None if no manager is configured.
    """
    if not _manager_arn:
        return None

    config_kwargs = {
        "payment_manager_arn": _manager_arn,
        "region": _region,
        "payment_instrument_id": instrument_id,
        "payment_session_id": session_id,
        "payment_connector_id": _connector_id,
    }

    config_kwargs["auto_payment"] = _auto_payment
    if _allowlist:
        config_kwargs["payment_tool_allowlist"] = _allowlist
    if _network_prefs:
        config_kwargs["network_preferences_config"] = _network_prefs

    if _process_payment_role_arn:
        # Only pass boto3_session if SDK supports it (added in bedrock-agentcore >= 1.11).
        # Older SDKs use the runtime role's default credentials and can still call ProcessPayment
        # if the runtime role has been granted permission directly.
        import inspect
        if "boto3_session" in inspect.signature(AgentCorePaymentsPluginConfig).parameters:
            config_kwargs["boto3_session"] = _assume_role_session(_process_payment_role_arn)
        else:
            logger.warning(
                "PROCESS_PAYMENT_ROLE_ARN set but bedrock-agentcore SDK does not support boto3_session. "
                "Upgrade to bedrock-agentcore>=1.11 to enable cross-role payment processing."
            )

    if _auth_mode == "bearer":
        bearer_token = os.getenv("AGENTCORE_BEARER_TOKEN")
        if bearer_token:
            config_kwargs["bearer_token"] = bearer_token
        else:
            logger.warning(
                "Bearer auth mode configured but AGENTCORE_BEARER_TOKEN not set. "
                "Falling back to SigV4. Set AGENTCORE_BEARER_TOKEN or pass bearer_token in invoke context."
            )
            config_kwargs["user_id"] = user_id or "default-user"
    else:
        config_kwargs["user_id"] = user_id or "default-user"

    config = AgentCorePaymentsPluginConfig(**config_kwargs)
    return AgentCorePaymentsPlugin(config=config)
