import { CONFIG_DIR, runSubprocessCapture } from '../../lib';
import { CDK_PROJECT_DIR } from '../constants';
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Manages the local CDK project generated by `agentcore create`.
 * Provides operations for validating, building, and managing the project.
 */
export class LocalCdkProject {
  readonly projectDir: string;

  /**
   * Create a LocalCdkProject from a base directory.
   * The CDK project is expected at `<baseDir>/agentcore/cdk`.
   */
  constructor(baseDir: string = process.cwd()) {
    this.projectDir = path.join(baseDir, CONFIG_DIR, CDK_PROJECT_DIR);
  }

  /**
   * Create a LocalCdkProject from an explicit project directory path.
   */
  static fromPath(projectDir: string): LocalCdkProject {
    const instance = Object.create(LocalCdkProject.prototype) as LocalCdkProject;
    (instance as { projectDir: string }).projectDir = projectDir;
    return instance;
  }

  /**
   * Check if the CDK project exists and has a valid structure.
   */
  exists(): boolean {
    const packageJson = path.join(this.projectDir, 'package.json');

    return fs.existsSync(this.projectDir) && fs.existsSync(packageJson);
  }

  /**
   * Validate that the project exists and is valid.
   * Throws an error if the project is missing or invalid.
   */
  validate(): void {
    if (!fs.existsSync(this.projectDir)) {
      throw new Error(`CDK project not found at ${this.projectDir}. Run 'agentcore create' first.`);
    }

    const packageJson = path.join(this.projectDir, 'package.json');

    if (!fs.existsSync(packageJson)) {
      throw new Error(`Invalid CDK project: missing package.json in ${this.projectDir}`);
    }
  }

  /**
   * Install npm dependencies.
   */
  async install(): Promise<void> {
    const result = await runSubprocessCapture('npm', ['install'], { cwd: this.projectDir });
    if (result.code !== 0) {
      const errorOutput = result.stderr || result.stdout || `npm exited with code ${result.code}`;
      throw new Error(errorOutput);
    }
  }

  /**
   * Build the project (compile TypeScript to JavaScript).
   */
  async build(): Promise<void> {
    const result = await runSubprocessCapture('npm', ['run', 'build'], { cwd: this.projectDir });
    if (result.code !== 0) {
      const errorOutput = result.stderr || result.stdout || `npm run build exited with code ${result.code}`;
      throw new Error(errorOutput);
    }
  }
}
